defaultLanguage: english

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  data:
    mongodb:
      port: 0
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://uaa.local.crdant.io:8443/token_keys
