spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.SecurityAutoConfiguration

management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"

defaultLanguage: spanish
