apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: gateway
  name: gateway
  namespace: gateway-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      run: gateway
  template:
    metadata:
      labels:
        run: gateway
    spec:
      containers:
      - image: crdant/greeting-api-gateway
        name: gateway
        ports:
        - containerPort: 8443
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: gateway-demo
spec:
  ports:
  - port: 8443
    protocol: TCP
    targetPort: 8443
  selector:
    run: gateway
  type: ClusterIP
