---
apiVersion: v1
kind: ConfigMap
metadata:
  name: configserver
  namespace: demo
data:
  SPRING_APPLICATION_JSON: |
    {
      "spring": {
        "profiles": {
          "active": "git"
        },
        "cloud": {
          "config": {
            "server": {
              "git": {
                "uri": "https://github.com/crdant/spring-cloud-gateway-demo",
                "searchPaths": "config/{application}/{profile}"
              }
            }
          }
        }
      }
    }
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-config-access-to-discovery
  namespace: demo
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: config-server
      app.kuberbetes.io/instance: config-server-standalone
      app.kubernetes.io/part-of: gateway-demo
  policyTypes:
  - Egress
  egress:
  - to:
    - podSelector:
        matchLabels:
          app.kubernetes.io/component: discovery
          app.kubernetes.io/part-of: gateway-demo
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: github-egress
  namespace: demo
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: config-server
      app.kuberbetes.io/instance: config-server-standalone
      app.kubernetes.io/part-of: gateway-demo
  policyTypes:
  - Egress
  egress:
  - to:
    - ipBlock:
        cidr: 192.30.252.0/22
    - ipBlock:
        cidr: 185.199.108.0/22
    - ipBlock:
        cidr: 140.82.112.0/20
    - ipBlock:
        cidr: 13.114.40.48/32
    - ipBlock:
        cidr: 13.229.188.59/32
    - ipBlock:
        cidr: 13.234.176.102/32
    - ipBlock:
        cidr: 13.234.210.38/32
    - ipBlock:
        cidr: 13.236.229.21/32
    - ipBlock:
        cidr: 13.237.44.5/32
    - ipBlock:
        cidr: 13.250.177.223/32
    - ipBlock:
        cidr: 15.164.81.167/32
    - ipBlock:
        cidr: 18.194.104.89/32
    - ipBlock:
        cidr: 18.195.85.27/32
    - ipBlock:
        cidr: 18.228.52.138/32
    - ipBlock:
        cidr: 18.228.67.229/32
    - ipBlock:
        cidr: 18.231.5.6/32
    - ipBlock:
        cidr: 35.159.8.160/32
    - ipBlock:
        cidr: 52.192.72.89/32
    - ipBlock:
        cidr: 52.64.108.95/32
    - ipBlock:
        cidr: 52.69.186.44/32
    - ipBlock:
        cidr: 52.74.223.119/32
    - ipBlock:
        cidr: 52.78.231.108/32
    ports:
    - protocol: TCP
      port: 443
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: configserver
  namespace: demo
  labels:
    run: configserver
    app.kubernetes.io/name: config-server
    app.kuberbetes.io/instance: config-server-standalone
    app.kubernetes.io/component: configuration
    app.kubernetes.io/part-of: gateway-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      run: configserver
  template:
    metadata:
      labels:
        run: configserver
        app.kubernetes.io/name: config-server
        app.kuberbetes.io/instance: config-server-standalone
        app.kubernetes.io/component: configuration
        app.kubernetes.io/part-of: gateway-demo
    spec:
      containers:
      - image: crdant/configserver
        name: configserver
        envFrom:
          - configMapRef:
              name: configserver
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: config
  namespace: demo
  labels:
    app.kubernetes.io/name: config-server
    app.kuberbetes.io/instance: config-server-standalone
    app.kubernetes.io/component: configuration
    app.kubernetes.io/part-of: gateway-demo
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    run: configserver
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: configserver
  namespace: demo
  labels:
    app.kubernetes.io/name: eureka
    app.kuberbetes.io/instance: eureka-standalone
    app.kubernetes.io/component: discovery
    app.kubernetes.io/part-of: gateway-demo
  annotations:
    nginx.org/ssl-services: "ssl-svc"
    cert-manager.io/cluster-issuer: "letsencrypt"
spec:
  tls:
  - hosts:
    - config.minikube.crdant.io
    secretName: configserver-tls
  rules:
  - host: config.minikube.crdant.io
    http:
      paths:
      - path: /
        backend:
          serviceName: config
          servicePort: 80
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: configserver-allow-access
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: config-server
      app.kuberbetes.io/instance: config-server-standalone
      app.kubernetes.io/part-of: gateway-demo
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app.kubernetes.io/component: services
          app.kubernetes.io/part-of: gateway-demo
    - podSelector:
        matchLabels:
          app.kubernetes.io/component: gateway
          app.kubernetes.io/part-of: gateway-demo
    ports:
    - protocol: TCP
      port: 8080

