---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka
  namespace: demo
  labels:
    run: eureka
    app.kubernetes.io/name: eureka
    app.kuberbetes.io/instance: eureka-standalone
    app.kubernetes.io/component: discovery
    app.kubernetes.io/part-of: gateway-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      run: eureka
  template:
    metadata:
      labels:
        run: eureka
        app.kubernetes.io/name: eureka
        app.kuberbetes.io/instance: eureka-standalone
        app.kubernetes.io/component: discovery
        app.kubernetes.io/part-of: gateway-demo
    spec:
      containers:
      - image: crdant/eureka
        name: eureka
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: discovery
  namespace: demo
  labels:
    app.kubernetes.io/name: eureka
    app.kuberbetes.io/instance: eureka-standalone
    app.kubernetes.io/component: discovery
    app.kubernetes.io/part-of: gateway-demo
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    run: eureka
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: eureka
  namespace: demo
  labels:
    app.kubernetes.io/name: eureka
    app.kuberbetes.io/instance: eureka-standalone
    app.kubernetes.io/component: discovery
    app.kubernetes.io/part-of: gateway-demo
  annotations:
    # nginx.org/ssl-services: "ssl-svc"
    cert-manager.io/cluster-issuer: "letsencrypt"
spec:
  tls:
  - hosts:
    - discovery.minikube.crdant.io
    secretName: discovery-tls
  rules:
  - host: discovery.minikube.crdant.io
    http:
      paths:
      - path: /
        backend:
          serviceName: discovery
          servicePort: 80
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: eureka-allow-discovery
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: eureka
      app.kuberbetes.io/instance: eureka-standalone
      app.kubernetes.io/part-of: gateway-demo
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app.kubernetes.io/component: services
          app.kubernetes.io/part-of: gateway-demo
    - podSelector:
        matchLabels:
          app.kubernetes.io/component: gateway
          app.kubernetes.io/part-of: gateway-demo
    ports:
    - protocol: TCP
      port: 8080

