---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-registry-access
  namespace: demo
spec:
  podSelector:
    matchExpressions:
    - key: build.pivotal.io/build 
      operator: Exists
      values: []
  policyTypes:
  - Egress
  egress:
  - to:
    ports:
    - protocol: TCP
      port: 443
    - protocol: UDP
      port: 53
---
apiVersion: build.pivotal.io/v1alpha1
kind: ClusterBuilder
metadata:
  name: kpack
  namespace: demo 
spec:
  image: cloudfoundry/cnb:bionic
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kpack
secrets:
- name: registry-credentials
