---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init
  namespace: demo
  labels:
    app: postgres
data:
  uaa.sh: |
    #!/bin/bash
    set -e

    psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-SQL
      CREATE USER uaa WITH PASSWORD 'restrain-whee-jealousy-typolog-potable';
      CREATE DATABASE uaa;
      GRANT ALL PRIVILEGES ON DATABASE uaa TO uaa;
    SQL
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      run: postgres
  template:
    metadata:
      labels:
        run: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:latest
        ports:
        - containerPort: 5432
        env:
        - name: PGDATA
          value: /data/postgres
        envFrom:
        - secretRef:
            name: postgres-auth
        volumeMounts:
        - name: init
          mountPath: /docker-entrypoint-initdb.d 
        - name: data
          mountPath: /data/postgres
      volumes:
      - name: init 
        configMap: 
          name: postgres-init
      - name: data
        persistentVolumeClaim:
          claimName: postgres
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: demo
spec:
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    run: postgres
  sessionAffinity: None
  type: ClusterIP
